import logging

logger = logging.getLogger('log')

DEFAULT_RETRY_AFTER = 10
RETRY_AFTER_HEADER = 'Retry-After'

SYNC_FULL_TYPE = 'full'
SYNC_INCREMENTAL_TYPE = 'incremental'
SYNC_TYPE = ((SYNC_FULL_TYPE, SYNC_FULL_TYPE), (SYNC_INCREMENTAL_TYPE, SYNC_INCREMENTAL_TYPE))
STATUS_FAILED = 'failed'
STATUS_SUCCESS = 'success'
STATUS_RUNNING = 'running'
STATUS_CANCELLED = 'cancelled'
STATUS_TYPE = ((STATUS_SUCCESS, STATUS_SUCCESS), (STATUS_FAILED, STATUS_FAILED), (STATUS_RUNNING, STATUS_RUNNING), (STATUS_CANCELLED, STATUS_CANCELLED))
MAX_LOG_SIZE = 4096

RELATIONSHIP_BATCH_SIZE = 20
SOFTWARE_INSTALL_BATCH_SIZE = 100
JOB_WAIT_SECONDS = 30
MAX_JOB_WAIT_SECONDS = 600  # 10 mins

TASK_DEVICES = "Devices"
TASK_BUSINESS_APPLICATIONS = "Business Applications"
ASSET_TYPE_BUSINESS_SERVICE = "Business Service"
ASSET_TYPE_SERVER = "Server"
ASSET_TYPE_UNIX_SERVER = "Unix Server"
ASSET_TYPE_WINDOWS_SERVER = "Windows Server"
ASSET_TYPE_HOST = "Host"
ASSET_TYPE_COMPUTER = "Computer"

ASSET_TYPE_VIRTUAL_MACHINE_DEPRECATED = 'Virtual Machine-deprecated'
ASSET_TYPE_AWS_VM_DEPRECATED = 'AWS VM-deprecated'
ASSET_TYPE_AZURE_VM_DEPRECATED = 'Azure VM-deprecated'
ASSET_TYPE_GCP_VM_DEPRECATED = 'GCP VM-deprecated'
ASSET_TYPE_VMWARE_VCENTER_VM_DEPRECATED = 'VMware VCenter VM-deprecated'
ASSET_TYPE_HOST_DEPRECATED = 'Host-deprecated'
ASSET_TYPE_VMWARE_VCENTER_HOST_DEPRECATED = 'VMware VCenter Host-deprecated'

ASSET_TYPE_COMPUTER = 'Computer'
ASSET_TYPE_AWS_VM = 'AWS VM'
ASSET_TYPE_AZURE_VM = 'Azure VM'
ASSET_TYPE_GCP_VM = 'GCP VM'
ASSET_TYPE_VMWARE_VCENTER_VM = 'VMware VCenter VM'
ASSET_TYPE_HOST = 'Host'
ASSET_TYPE_VMWARE_VCENTER_HOST = 'VMware VCenter Host'
ASSET_TYPE_LOAD_BALANCER = 'Load Balancer'
ASSET_TYPE_AZURE_LB = 'Azure LB'
ASSET_TYPE_MOBILE = 'Mobile'
ASSET_TYPE_VMWARE_VCENTER_IMAGE = 'VMware VCenter Image'
ASSET_TYPE_AWS_K8S_NODE_DEPRECATED = 'AWS K8s Node-deprecated'
ASSET_TYPE_AWS_K8S_NODE = 'AWS K8s Node'

CACHE_ASSET_TYPES = 'asset_types'
CACHE_ASSETS = 'assets'
CACHE_TRASH_ASSETS = 'trash_assets'
CACHE_SOFTWARES = 'softwares'
CACHE_CONTRACTS = 'contracts'
CACHE_PRODUCTS = 'products'
CACHE_COMPONENTS = 'components'

D42_CACHE_SERIAL_NUMBER_DEVICE_COUNTS = 'serial_number_device_counts'